// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.spring.exampleroo.domain;

import com.spring.exampleroo.domain.PizzaDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PizzaDataOnDemand_Roo_Configurable {
    
    declare @type: PizzaDataOnDemand: @Configurable;
    
}
